### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ldowen** [AMReX-Combustion/PeleMP#7]
- [x] Ensure particles don't reflect off an EB or boundary and end up behind an EB or boundary
- [ ] Setup HDF5 file format writing for sprays in PeleC, PeleLM, and PeleLMeX
- [ ] Change soot model to utilize new `ParallelFor` over entire domain instead of being box specific
- [x] Setup restarting sprays from plt files
- [ ] Fix visualizing particles with ParaView
- [x] Add more template types for spray injection (ie pressure-swirl injector etc)
- [x] Add checks to ensure virtual particles aren't created behind EB
- [ ] Create documentation for models and equations used in spray and soot functions
- [ ] Create documentation for spray utilizing functionality
- [ ] Create documentation for soot utilizing functionality
- [x] Mitigate issues caused by excessive spray source terms occurring near small EB cells
- [ ] Add function to write to checkpoint to ensure mass injection is not interrupted on stop and restart

Stretch goals:
- [ ] Add spray breakup model
- [ ] Add wall film model
- [ ] Improve interpolation scheme for droplets
